import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { Alert, Platform } from 'react-native';

// ============================
// PDF HTML Template Helpers
// ============================

const getHeaderHTML = (title, subtitle) => {
  return '<div style="background: linear-gradient(135deg, #007BFF, #0056b3); padding: 30px; color: white;">' +
    '<h1 style="margin:0; font-size:28px; font-weight:800;">ThabStay</h1>' +
    '<h2 style="margin:5px 0 0; font-size:20px; font-weight:400;">' + title + '</h2>' +
    '<p style="margin:5px 0 0; font-size:13px; opacity:0.85;">' + subtitle + '</p>' +
    '</div>';
};

const getFooterHTML = () => {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return '<div style="margin-top:30px; padding:15px; text-align:center; border-top:2px solid #eee; color:#999; font-size:11px;">' +
    'Generated by <strong>ThabStay</strong> &bull; ' + dateStr + ' &bull; Confidential' +
    '</div>';
};

const getStatBoxHTML = (stats) => {
  let boxes = '';
  for (let i = 0; i < stats.length; i++) {
    const s = stats[i];
    boxes += '<div style="flex:1; background:#f8f9fa; border-radius:10px; padding:15px; text-align:center; margin:0 5px; border-left:4px solid ' + s.color + ';">' +
      '<div style="font-size:24px; font-weight:bold; color:' + s.color + ';">' + s.value + '</div>' +
      '<div style="font-size:12px; color:#666; text-transform:uppercase; margin-top:5px;">' + s.label + '</div>' +
      '</div>';
  }
  return '<div style="display:flex; margin:20px 15px;">' + boxes + '</div>';
};

const getTableHTML = (headers, rows) => {
  let headerCells = '';
  for (let i = 0; i < headers.length; i++) {
    headerCells += '<th style="background:#007BFF; color:white; padding:10px 12px; text-align:left; font-size:12px; text-transform:uppercase;">' + headers[i] + '</th>';
  }

  let bodyRows = '';
  for (let i = 0; i < rows.length; i++) {
    const bg = i % 2 === 0 ? '#ffffff' : '#f8f9fb';
    let cells = '';
    for (let j = 0; j < rows[i].length; j++) {
      cells += '<td style="padding:10px 12px; border-bottom:1px solid #eee; font-size:13px; color:#333;">' + rows[i][j] + '</td>';
    }
    bodyRows += '<tr style="background:' + bg + ';">' + cells + '</tr>';
  }

  return '<table style="width:100%; border-collapse:collapse; margin:15px 0;">' +
    '<thead><tr>' + headerCells + '</tr></thead>' +
    '<tbody>' + bodyRows + '</tbody>' +
    '</table>';
};

const wrapHTML = (body) => {
  return '<html><head><meta charset="utf-8"><style>' +
    'body { font-family: Arial, Helvetica, sans-serif; margin:0; padding:0; color:#333; }' +
    'h3 { color:#333; margin:20px 15px 10px; font-size:18px; }' +
    '</style></head><body>' + body + '</body></html>';
};

// ============================
// PDF Generators
// ============================

export const generatePropertiesPDF = async (listings, dateRange) => {
  const totalSpots = listings.reduce((a, h) => a + (Number(h.availableSpots) || 0), 0);
  const avgPrice = listings.length > 0 ? (listings.reduce((a, h) => a + (Number(h.price) || 0), 0) / listings.length).toFixed(0) : '0';

  const stats = [
    { label: 'Total Properties', value: listings.length, color: '#007BFF' },
    { label: 'Total Spots', value: totalSpots, color: '#4CAF50' },
    { label: 'Avg Price', value: '$' + avgPrice, color: '#FF9800' },
  ];

  const headers = ['#', 'Title', 'Location', 'Price', 'Spots', 'Gender'];
  const rows = listings.map((h, i) => [
    i + 1,
    h.title || 'N/A',
    h.location || 'N/A',
    '$' + (h.price || 0),
    h.availableSpots || 0,
    h.genderPolicy || 'Mixed'
  ]);

  const subtitle = dateRange || ('Generated on ' + new Date().toDateString());
  const html = wrapHTML(
    getHeaderHTML('Properties Report', subtitle) +
    getStatBoxHTML(stats) +
    '<h3>Property Listings</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await exportPDF(html, 'Properties_Report');
};

export const generateBookingsPDF = async (bookings, dateRange) => {
  const pending = bookings.filter(b => b.status === 'pending').length;
  const accepted = bookings.filter(b => b.status === 'accepted').length;
  const paid = bookings.filter(b => b.status === 'paid').length;
  const rejected = bookings.filter(b => b.status === 'rejected').length;

  const stats = [
    { label: 'Pending', value: pending, color: '#FFC107' },
    { label: 'Accepted', value: accepted, color: '#4CAF50' },
    { label: 'Paid', value: paid, color: '#2196F3' },
    { label: 'Rejected', value: rejected, color: '#D32F2F' },
  ];

  const headers = ['#', 'Property', 'Student', 'Amount', 'Status', 'Date'];
  const rows = bookings.map((b, i) => [
    i + 1,
    b.houseName || b.houseTitle || 'N/A',
    b.studentEmail || b.studentName || 'N/A',
    '$' + (b.amount || 0),
    (b.status || 'N/A').charAt(0).toUpperCase() + (b.status || '').slice(1),
    b.timestamp ? new Date(b.timestamp).toLocaleDateString() : 'N/A'
  ]);

  const subtitle = dateRange || ('Total: ' + bookings.length + ' bookings');
  const html = wrapHTML(
    getHeaderHTML('Booking Summary Report', subtitle) +
    getStatBoxHTML(stats) +
    '<h3>All Bookings</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await exportPDF(html, 'Booking_Summary');
};

export const generateRevenuePDF = async (bookings, dateRange) => {
  const paidBookings = bookings.filter(b => b.status === 'paid');
  const totalRevenue = paidBookings.reduce((a, b) => a + (Number(b.amount) || 0), 0);
  const avgTx = paidBookings.length > 0 ? (totalRevenue / paidBookings.length).toFixed(0) : '0';

  const stats = [
    { label: 'Total Revenue', value: '$' + totalRevenue, color: '#4CAF50' },
    { label: 'Transactions', value: paidBookings.length, color: '#2196F3' },
    { label: 'Avg Transaction', value: '$' + avgTx, color: '#FF9800' },
  ];

  const headers = ['#', 'Property', 'Student', 'Amount', 'Trans ID', 'Date'];
  const rows = paidBookings.map((b, i) => [
    i + 1,
    b.houseName || b.houseTitle || 'N/A',
    b.studentEmail || 'N/A',
    '$' + (b.amount || 0),
    b.transactionId || 'N/A',
    b.paymentDate ? new Date(b.paymentDate).toLocaleDateString() : 'N/A'
  ]);

  rows.push(['', '', '', '<b>$' + totalRevenue + '</b>', '', '<b>TOTAL</b>']);

  const subtitle = dateRange || ('Total Revenue: $' + totalRevenue);
  const html = wrapHTML(
    getHeaderHTML('Revenue Report', subtitle) +
    getStatBoxHTML(stats) +
    '<h3>Payment Transactions</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await exportPDF(html, 'Revenue_Report');
};

// ============================
// Admin PDF Generators
// ============================

export const generatePlatformOverviewPDF = async (users, houses, dateRange) => {
  const students = users.filter(u => u.role === 'student').length;
  const landlords = users.filter(u => u.role === 'landlord').length;
  const admins = users.filter(u => u.role === 'admin').length;

  const stats = [
    { label: 'Total Users', value: users.length, color: '#007BFF' },
    { label: 'Students', value: students, color: '#4CAF50' },
    { label: 'Landlords', value: landlords, color: '#FF9800' },
    { label: 'Listings', value: houses.length, color: '#9C27B0' },
  ];

  const locationCounts = {};
  houses.forEach(h => {
    const loc = h.location || 'Unknown';
    locationCounts[loc] = (locationCounts[loc] || 0) + 1;
  });

  const locHeaders = ['Location', 'Listings', 'Percentage'];
  const locRows = Object.entries(locationCounts).map(([loc, count]) => [
    loc, count, ((count / (houses.length || 1)) * 100).toFixed(1) + '%'
  ]);

  const usersTotal = users.length || 1;
  const subtitle = dateRange || ('System snapshot - ' + new Date().toDateString());
  const html = wrapHTML(
    getHeaderHTML('Platform Overview Report', subtitle) +
    getStatBoxHTML(stats) +
    '<h3>Listings by Location</h3>' +
    getTableHTML(locHeaders, locRows) +
    '<h3>User Role Distribution</h3>' +
    getTableHTML(['Role', 'Count', 'Percentage'], [
      ['Students', students, ((students / usersTotal) * 100).toFixed(1) + '%'],
      ['Landlords', landlords, ((landlords / usersTotal) * 100).toFixed(1) + '%'],
      ['Admins', admins, ((admins / usersTotal) * 100).toFixed(1) + '%'],
    ]) +
    getFooterHTML()
  );

  await exportPDF(html, 'Platform_Overview');
};

export const generateAllPaymentsPDF = async (payments, dateRange) => {
  const totalRevenue = payments.reduce((a, p) => a + (Number(p.amount) || 0), 0);

  const stats = [
    { label: 'Total Revenue', value: '$' + totalRevenue, color: '#4CAF50' },
    { label: 'Transactions', value: payments.length, color: '#2196F3' },
  ];

  const headers = ['#', 'Property', 'Student', 'Amount', 'Trans ID', 'Date'];
  const rows = payments.map((p, i) => [
    i + 1,
    p.houseName || 'N/A',
    p.studentEmail || 'N/A',
    '$' + (p.amount || 0),
    p.transactionId || 'N/A',
    p.paymentDate ? new Date(p.paymentDate).toLocaleDateString() : 'N/A'
  ]);
  rows.push(['', '', '<b>TOTAL</b>', '<b>$' + totalRevenue + '</b>', '', '']);

  const subtitle = dateRange || (payments.length + ' transactions recorded');
  const html = wrapHTML(
    getHeaderHTML('All Payments Report', subtitle) +
    getStatBoxHTML(stats) +
    '<h3>Payment Transactions</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await exportPDF(html, 'All_Payments');
};

export const generateUsersPDF = async (users, dateRange) => {
  const headers = ['#', 'Name', 'Email', 'Role', 'Verified'];
  const rows = users.map((u, i) => [
    i + 1,
    u.username || u.name || 'N/A',
    u.email || 'N/A',
    (u.role || 'N/A').charAt(0).toUpperCase() + (u.role || '').slice(1),
    u.verificationStatus === 'verified' ? 'Yes' : 'No'
  ]);

  const verified = users.filter(u => u.verificationStatus === 'verified').length;
  const subtitle = dateRange || (users.length + ' registered users');
  const html = wrapHTML(
    getHeaderHTML('User Management Report', subtitle) +
    getStatBoxHTML([
      { label: 'Total Users', value: users.length, color: '#007BFF' },
      { label: 'Verified', value: verified, color: '#4CAF50' },
    ]) +
    '<h3>All Users</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await exportPDF(html, 'User_Report');
};

export const generateIssuesPDF = async (reports, dateRange) => {
  const headers = ['#', 'Type', 'Reporter', 'Role', 'Description', 'Date'];
  const rows = reports.map((r, i) => {
    const desc = r.description || '';
    return [
      i + 1,
      r.type || 'Issue',
      r.reporterEmail || 'N/A',
      r.reporterRole || 'N/A',
      desc.length > 60 ? desc.substring(0, 60) + '...' : desc,
      r.timestamp ? new Date(r.timestamp).toLocaleDateString() : 'N/A'
    ];
  });

  const subtitle = dateRange || (reports.length + ' reports submitted');
  const html = wrapHTML(
    getHeaderHTML('Issue Reports', subtitle) +
    '<h3>All Reported Issues</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await exportPDF(html, 'Issue_Reports');
};

// ============================
// CSV (Excel) Generators
// ============================

const escapeCSV = (val) => {
  const str = String(val != null ? val : '');
  if (str.indexOf(',') >= 0 || str.indexOf('"') >= 0 || str.indexOf('\n') >= 0) {
    return '"' + str.replace(/"/g, '""') + '"';
  }
  return str;
};

export const generateCSV = async (headers, rows, filename) => {
  try {
    const lines = [];
    lines.push(headers.map(escapeCSV).join(','));
    for (let i = 0; i < rows.length; i++) {
      lines.push(rows[i].map(escapeCSV).join(','));
    }
    const csvContent = lines.join('\n');

    const fileUri = FileSystem.documentDirectory + filename + '.csv';
    await FileSystem.writeAsStringAsync(fileUri, csvContent, { encoding: FileSystem.EncodingType.UTF8 });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(fileUri, { 
        mimeType: 'text/csv', 
        dialogTitle: 'Export ' + filename,
        UTI: 'public.comma-separated-values-text'
      });
    } else {
      Alert.alert('Success', 'Report saved successfully.');
    }
  } catch (error) {
    console.error('CSV Generation Error:', error);
    Alert.alert('Error', 'Failed to generate Excel report: ' + (error.message || ''));
  }
};

export const generatePropertiesCSV = async (listings) => {
  const headers = ['Title', 'Location', 'Price ($)', 'Available Spots', 'Gender Policy', 'Date Listed'];
  const rows = listings.map(h => [
    h.title || '', h.location || '', h.price || 0, h.availableSpots || 0, h.genderPolicy || 'Mixed',
    h.createdAt ? new Date(h.createdAt).toLocaleDateString() : 'N/A'
  ]);
  await generateCSV(headers, rows, 'Properties_Report');
};

export const generateBookingsCSV = async (bookings) => {
  const headers = ['Property', 'Student', 'Amount ($)', 'Status', 'Transaction ID', 'Date'];
  const rows = bookings.map(b => [
    b.houseName || b.houseTitle || '', b.studentEmail || b.studentName || '', b.amount || 0,
    b.status || '', b.transactionId || 'N/A',
    b.timestamp ? new Date(b.timestamp).toLocaleDateString() : 'N/A'
  ]);
  await generateCSV(headers, rows, 'Bookings_Report');
};

export const generatePaymentsCSV = async (payments) => {
  const headers = ['Property', 'Student', 'Amount ($)', 'Transaction ID', 'Payment Date'];
  const rows = payments.map(p => [
    p.houseName || '', p.studentEmail || '', p.amount || 0, p.transactionId || 'N/A',
    p.paymentDate ? new Date(p.paymentDate).toLocaleDateString() : 'N/A'
  ]);
  await generateCSV(headers, rows, 'Payments_Report');
};

export const generateUsersCSV = async (users) => {
  const headers = ['Name', 'Email', 'Role', 'Verification Status'];
  const rows = users.map(u => [
    u.username || u.name || 'N/A', u.email || '', u.role || '',
    u.verificationStatus === 'verified' ? 'Verified' : 'Not Verified'
  ]);
  await generateCSV(headers, rows, 'Users_Report');
};

// ============================
// Helper: Export PDF via file
// ============================

const exportPDF = async (html, filename) => {
  try {
    // Generate PDF file from HTML
    const result = await Print.printToFileAsync({
      html: html,
      width: 612,  // US Letter width in points
      height: 792, // US Letter height in points
    });
    
    // Move to a readable location with proper name
    const newUri = FileSystem.documentDirectory + filename + '_' + Date.now() + '.pdf';
    await FileSystem.moveAsync({ from: result.uri, to: newUri });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(newUri, { 
        mimeType: 'application/pdf', 
        dialogTitle: 'Share ' + filename,
        UTI: 'com.adobe.pdf'
      });
    } else {
      Alert.alert('Success', 'PDF report generated successfully.');
    }
  } catch (error) {
    console.error('PDF Generation Error:', error);
    Alert.alert('Error', 'Failed to generate PDF: ' + (error.message || ''));
  }
};
