import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { Alert } from 'react-native';

// ============================
// PDF HTML Template Helpers
// ============================

const getHeaderHTML = (title, subtitle) => `
  <div style="background: linear-gradient(135deg, #007BFF, #0056b3); padding: 30px; color: white; border-radius: 0 0 15px 15px;">
    <h1 style="margin:0; font-size:28px; font-weight:800;">ThabStay</h1>
    <h2 style="margin:5px 0 0; font-size:20px; font-weight:400;">${title}</h2>
    <p style="margin:5px 0 0; font-size:13px; opacity:0.85;">${subtitle}</p>
  </div>
`;

const getFooterHTML = () => `
  <div style="margin-top:30px; padding:15px; text-align:center; border-top:2px solid #eee; color:#999; font-size:11px;">
    Generated by <strong>ThabStay</strong> • ${new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' })} • Confidential
  </div>
`;

const getStatBoxHTML = (stats) => {
  const boxes = stats.map(s => `
    <div style="flex:1; background:#f8f9fa; border-radius:10px; padding:15px; text-align:center; margin:0 5px; border-left:4px solid ${s.color};">
      <div style="font-size:24px; font-weight:bold; color:${s.color};">${s.value}</div>
      <div style="font-size:12px; color:#666; text-transform:uppercase; margin-top:5px;">${s.label}</div>
    </div>
  `).join('');
  return `<div style="display:flex; margin:20px 15px;">${boxes}</div>`;
};

const getTableHTML = (headers, rows) => {
  const headerCells = headers.map(h => `<th style="background:#007BFF; color:white; padding:10px 12px; text-align:left; font-size:12px; text-transform:uppercase;">${h}</th>`).join('');
  const bodyRows = rows.map((row, i) => {
    const bg = i % 2 === 0 ? '#ffffff' : '#f8f9fb';
    const cells = row.map(cell => `<td style="padding:10px 12px; border-bottom:1px solid #eee; font-size:13px; color:#333;">${cell}</td>`).join('');
    return `<tr style="background:${bg};">${cells}</tr>`;
  }).join('');
  return `
    <table style="width:100%; border-collapse:collapse; margin:15px 0; border-radius:8px; overflow:hidden; box-shadow:0 1px 3px rgba(0,0,0,0.1);">
      <thead><tr>${headerCells}</tr></thead>
      <tbody>${bodyRows}</tbody>
    </table>
  `;
};

const wrapHTML = (body) => `
  <html>
  <head>
    <meta charset="utf-8">
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin:0; padding:0; color:#333; }
      h3 { color:#333; margin:20px 15px 10px; font-size:18px; }
    </style>
  </head>
  <body>${body}</body>
  </html>
`;

// ============================
// PDF Generators
// ============================

export const generatePropertiesPDF = async (listings) => {
  const stats = [
    { label: 'Total Properties', value: listings.length, color: '#007BFF' },
    { label: 'Total Spots', value: listings.reduce((a, h) => a + (Number(h.availableSpots) || 0), 0), color: '#4CAF50' },
    { label: 'Avg Price', value: `$${(listings.reduce((a, h) => a + (Number(h.price) || 0), 0) / (listings.length || 1)).toFixed(0)}`, color: '#FF9800' },
  ];

  const headers = ['#', 'Title', 'Location', 'Price', 'Spots', 'Gender Policy'];
  const rows = listings.map((h, i) => [
    i + 1,
    h.title || 'N/A',
    h.location || 'N/A',
    `$${h.price}`,
    h.availableSpots || 0,
    h.genderPolicy || 'Mixed'
  ]);

  const html = wrapHTML(
    getHeaderHTML('Properties Report', `Generated on ${new Date().toDateString()}`) +
    getStatBoxHTML(stats) +
    '<h3>Property Listings</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await printOrShare(html, 'Properties_Report');
};

export const generateBookingsPDF = async (bookings) => {
  const pending = bookings.filter(b => b.status === 'pending').length;
  const accepted = bookings.filter(b => b.status === 'accepted').length;
  const paid = bookings.filter(b => b.status === 'paid').length;
  const rejected = bookings.filter(b => b.status === 'rejected').length;

  const stats = [
    { label: 'Pending', value: pending, color: '#FFC107' },
    { label: 'Accepted', value: accepted, color: '#4CAF50' },
    { label: 'Paid', value: paid, color: '#2196F3' },
    { label: 'Rejected', value: rejected, color: '#D32F2F' },
  ];

  const headers = ['#', 'Property', 'Student', 'Amount', 'Status', 'Date'];
  const rows = bookings.map((b, i) => [
    i + 1,
    b.houseName || b.houseTitle || 'N/A',
    b.studentEmail || b.studentName || 'N/A',
    `$${b.amount || 0}`,
    (b.status || 'N/A').charAt(0).toUpperCase() + (b.status || '').slice(1),
    b.timestamp ? new Date(b.timestamp).toLocaleDateString() : 'N/A'
  ]);

  const html = wrapHTML(
    getHeaderHTML('Booking Summary Report', `Total: ${bookings.length} bookings`) +
    getStatBoxHTML(stats) +
    '<h3>All Bookings</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await printOrShare(html, 'Booking_Summary');
};

export const generateRevenuePDF = async (bookings) => {
  const paidBookings = bookings.filter(b => b.status === 'paid');
  const totalRevenue = paidBookings.reduce((a, b) => a + (Number(b.amount) || 0), 0);

  const stats = [
    { label: 'Total Revenue', value: `$${totalRevenue}`, color: '#4CAF50' },
    { label: 'Transactions', value: paidBookings.length, color: '#2196F3' },
    { label: 'Avg Transaction', value: `$${(totalRevenue / (paidBookings.length || 1)).toFixed(0)}`, color: '#FF9800' },
  ];

  const headers = ['#', 'Property', 'Student', 'Amount', 'Transaction ID', 'Payment Date'];
  const rows = paidBookings.map((b, i) => [
    i + 1,
    b.houseName || b.houseTitle || 'N/A',
    b.studentEmail || 'N/A',
    `$${b.amount || 0}`,
    b.transactionId || 'N/A',
    b.paymentDate ? new Date(b.paymentDate).toLocaleDateString() : 'N/A'
  ]);

  // Add total row
  rows.push(['', '', '', `<strong>$${totalRevenue}</strong>`, '', '<strong>TOTAL</strong>']);

  const html = wrapHTML(
    getHeaderHTML('Revenue Report', `Total Revenue: $${totalRevenue}`) +
    getStatBoxHTML(stats) +
    '<h3>Payment Transactions</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await printOrShare(html, 'Revenue_Report');
};

// ============================
// Admin PDF Generators
// ============================

export const generatePlatformOverviewPDF = async (users, houses) => {
  const students = users.filter(u => u.role === 'student').length;
  const landlords = users.filter(u => u.role === 'landlord').length;
  const admins = users.filter(u => u.role === 'admin').length;

  const stats = [
    { label: 'Total Users', value: users.length, color: '#007BFF' },
    { label: 'Students', value: students, color: '#4CAF50' },
    { label: 'Landlords', value: landlords, color: '#FF9800' },
    { label: 'Listings', value: houses.length, color: '#9C27B0' },
  ];

  // Location breakdown
  const locationCounts = {};
  houses.forEach(h => {
    const loc = h.location || 'Unknown';
    locationCounts[loc] = (locationCounts[loc] || 0) + 1;
  });

  const locHeaders = ['Location', 'Number of Listings', 'Percentage'];
  const locRows = Object.entries(locationCounts).map(([loc, count]) => [
    loc,
    count,
    `${((count / (houses.length || 1)) * 100).toFixed(1)}%`
  ]);

  const html = wrapHTML(
    getHeaderHTML('Platform Overview Report', `System snapshot — ${new Date().toDateString()}`) +
    getStatBoxHTML(stats) +
    '<h3>Listings by Location</h3>' +
    getTableHTML(locHeaders, locRows) +
    '<h3>User Role Distribution</h3>' +
    getTableHTML(['Role', 'Count', 'Percentage'], [
      ['Students', students, `${((students / (users.length || 1)) * 100).toFixed(1)}%`],
      ['Landlords', landlords, `${((landlords / (users.length || 1)) * 100).toFixed(1)}%`],
      ['Admins', admins, `${((admins / (users.length || 1)) * 100).toFixed(1)}%`],
    ]) +
    getFooterHTML()
  );

  await printOrShare(html, 'Platform_Overview');
};

export const generateAllPaymentsPDF = async (payments) => {
  const totalRevenue = payments.reduce((a, p) => a + (Number(p.amount) || 0), 0);

  const stats = [
    { label: 'Total Revenue', value: `$${totalRevenue}`, color: '#4CAF50' },
    { label: 'Transactions', value: payments.length, color: '#2196F3' },
  ];

  const headers = ['#', 'Property', 'Student', 'Amount', 'Transaction ID', 'Date'];
  const rows = payments.map((p, i) => [
    i + 1,
    p.houseName || 'N/A',
    p.studentEmail || 'N/A',
    `$${p.amount || 0}`,
    p.transactionId || 'N/A',
    p.paymentDate ? new Date(p.paymentDate).toLocaleDateString() : 'N/A'
  ]);
  rows.push(['', '', '<strong>TOTAL</strong>', `<strong>$${totalRevenue}</strong>`, '', '']);

  const html = wrapHTML(
    getHeaderHTML('All Payments Report', `${payments.length} transactions recorded`) +
    getStatBoxHTML(stats) +
    '<h3>Payment Transactions</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await printOrShare(html, 'All_Payments');
};

export const generateUsersPDF = async (users) => {
  const headers = ['#', 'Name', 'Email', 'Role', 'Verified'];
  const rows = users.map((u, i) => [
    i + 1,
    u.username || u.name || 'N/A',
    u.email || 'N/A',
    (u.role || 'N/A').charAt(0).toUpperCase() + (u.role || '').slice(1),
    u.verificationStatus === 'verified' ? '✅ Yes' : '❌ No'
  ]);

  const html = wrapHTML(
    getHeaderHTML('User Management Report', `${users.length} registered users`) +
    getStatBoxHTML([
      { label: 'Total Users', value: users.length, color: '#007BFF' },
      { label: 'Verified', value: users.filter(u => u.verificationStatus === 'verified').length, color: '#4CAF50' },
    ]) +
    '<h3>All Users</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await printOrShare(html, 'User_Report');
};

export const generateIssuesPDF = async (reports) => {
  const headers = ['#', 'Type', 'Reporter', 'Role', 'Description', 'Date'];
  const rows = reports.map((r, i) => [
    i + 1,
    r.type || 'Issue',
    r.reporterEmail || 'N/A',
    r.reporterRole || 'N/A',
    (r.description || '').substring(0, 60) + ((r.description || '').length > 60 ? '...' : ''),
    r.timestamp ? new Date(r.timestamp).toLocaleDateString() : 'N/A'
  ]);

  const html = wrapHTML(
    getHeaderHTML('Issue Reports', `${reports.length} reports submitted`) +
    '<h3>All Reported Issues</h3>' +
    getTableHTML(headers, rows) +
    getFooterHTML()
  );

  await printOrShare(html, 'Issue_Reports');
};

// ============================
// CSV (Excel) Generators
// ============================

const escapeCSV = (val) => {
  const str = String(val || '');
  return str.includes(',') || str.includes('"') || str.includes('\n')
    ? `"${str.replace(/"/g, '""')}"` : str;
};

export const generateCSV = async (headers, rows, filename) => {
  try {
    const csvContent = [
      headers.map(escapeCSV).join(','),
      ...rows.map(row => row.map(escapeCSV).join(','))
    ].join('\n');

    const fileUri = FileSystem.documentDirectory + `${filename}.csv`;
    await FileSystem.writeAsStringAsync(fileUri, csvContent, { encoding: FileSystem.EncodingType.UTF8 });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(fileUri, { mimeType: 'text/csv', dialogTitle: `Export ${filename}` });
    } else {
      Alert.alert('Success', `Report saved to: ${fileUri}`);
    }
  } catch (error) {
    console.error('CSV Generation Error:', error);
    Alert.alert('Error', 'Failed to generate CSV report.');
  }
};

export const generatePropertiesCSV = async (listings) => {
  const headers = ['Title', 'Location', 'Price ($)', 'Available Spots', 'Gender Policy', 'Date Listed'];
  const rows = listings.map(h => [
    h.title, h.location, h.price, h.availableSpots || 0, h.genderPolicy || 'Mixed',
    h.createdAt ? new Date(h.createdAt).toLocaleDateString() : 'N/A'
  ]);
  await generateCSV(headers, rows, 'Properties_Report');
};

export const generateBookingsCSV = async (bookings) => {
  const headers = ['Property', 'Student', 'Amount ($)', 'Status', 'Transaction ID', 'Date'];
  const rows = bookings.map(b => [
    b.houseName || b.houseTitle, b.studentEmail || b.studentName, b.amount || 0,
    b.status, b.transactionId || 'N/A',
    b.timestamp ? new Date(b.timestamp).toLocaleDateString() : 'N/A'
  ]);
  await generateCSV(headers, rows, 'Bookings_Report');
};

export const generatePaymentsCSV = async (payments) => {
  const headers = ['Property', 'Student', 'Amount ($)', 'Transaction ID', 'Payment Date'];
  const rows = payments.map(p => [
    p.houseName, p.studentEmail, p.amount || 0, p.transactionId || 'N/A',
    p.paymentDate ? new Date(p.paymentDate).toLocaleDateString() : 'N/A'
  ]);
  await generateCSV(headers, rows, 'Payments_Report');
};

export const generateUsersCSV = async (users) => {
  const headers = ['Name', 'Email', 'Role', 'Verification Status'];
  const rows = users.map(u => [
    u.username || u.name || 'N/A', u.email, u.role,
    u.verificationStatus === 'verified' ? 'Verified' : 'Not Verified'
  ]);
  await generateCSV(headers, rows, 'Users_Report');
};

// ============================
// Helper: Print or Share PDF
// ============================

const printOrShare = async (html, filename) => {
  try {
    const { uri } = await Print.printToFileAsync({ html });
    
    // Rename file
    const newUri = FileSystem.documentDirectory + `${filename}_${Date.now()}.pdf`;
    await FileSystem.moveAsync({ from: uri, to: newUri });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(newUri, { mimeType: 'application/pdf', dialogTitle: `Share ${filename}` });
    } else {
      Alert.alert('Success', `Report saved to: ${newUri}`);
    }
  } catch (error) {
    console.error('PDF Generation Error:', error);
    Alert.alert('Error', 'Failed to generate PDF report.');
  }
};
