import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { Alert, Platform } from 'react-native';

// ============================
// Professional PDF HTML Template
// ============================

const PDF_STYLES = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #2d3748; background: #fff; }
  .header {
    background: linear-gradient(135deg, #1a365d 0%, #2b6cb0 50%, #3182ce 100%);
    padding: 35px 30px; color: #fff; position: relative; overflow: hidden;
  }
  .header::after {
    content: ''; position: absolute; top: -50%; right: -10%; width: 300px; height: 300px;
    background: rgba(255,255,255,0.05); border-radius: 50%;
  }
  .header .brand { font-size: 14px; letter-spacing: 3px; text-transform: uppercase; opacity: 0.7; margin-bottom: 8px; }
  .header .title { font-size: 26px; font-weight: 700; margin-bottom: 4px; }
  .header .subtitle { font-size: 13px; opacity: 0.85; }
  .header .date-badge {
    display: inline-block; background: rgba(255,255,255,0.15); padding: 6px 14px;
    border-radius: 20px; font-size: 12px; margin-top: 12px;
  }
  .stats-row { display: flex; padding: 20px 25px; gap: 15px; }
  .stat-card {
    flex: 1; background: #f7fafc; border-radius: 10px; padding: 18px; text-align: center;
    border: 1px solid #e2e8f0;
  }
  .stat-value { font-size: 28px; font-weight: 800; margin-bottom: 4px; }
  .stat-label { font-size: 11px; color: #718096; text-transform: uppercase; letter-spacing: 1px; }
  .section-title {
    font-size: 16px; font-weight: 700; color: #1a365d; padding: 15px 25px 10px;
    border-bottom: 2px solid #e2e8f0; margin: 10px 25px 0; display: flex;
    align-items: center; gap: 8px;
  }
  .section-title::before { content: ''; width: 4px; height: 20px; background: #3182ce; border-radius: 2px; display: inline-block; }
  table { width: calc(100% - 50px); margin: 12px 25px; border-collapse: separate; border-spacing: 0; border-radius: 8px; overflow: hidden; border: 1px solid #e2e8f0; }
  thead th {
    background: #1a365d; color: #fff; padding: 12px 14px; text-align: left;
    font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; font-weight: 600;
  }
  tbody td { padding: 10px 14px; font-size: 12px; border-bottom: 1px solid #edf2f7; color: #4a5568; }
  tbody tr:nth-child(even) { background: #f7fafc; }
  tbody tr:last-child td { border-bottom: none; }
  tbody tr.total-row { background: #ebf4ff; font-weight: 700; }
  tbody tr.total-row td { color: #1a365d; border-top: 2px solid #3182ce; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 11px; font-weight: 600; }
  .badge-pending { background: #fefcbf; color: #975a16; }
  .badge-accepted { background: #c6f6d5; color: #276749; }
  .badge-paid { background: #bee3f8; color: #2a4365; }
  .badge-rejected { background: #fed7d7; color: #9b2c2c; }
  .footer {
    margin-top: 30px; padding: 20px 25px; border-top: 2px solid #e2e8f0;
    display: flex; justify-content: space-between; align-items: center;
  }
  .footer-left { font-size: 11px; color: #a0aec0; }
  .footer-right { font-size: 10px; color: #cbd5e0; text-align: right; }
  .footer-brand { font-weight: 700; color: #3182ce; }
  .empty-state { text-align: center; padding: 40px 25px; color: #a0aec0; font-size: 14px; }
`;

const buildHTML = (headerTitle, headerSubtitle, dateRange, body) => {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  return '<html><head><meta charset="utf-8"><style>' + PDF_STYLES + '</style></head><body>' +
    '<div class="header">' +
      '<div class="brand">ThabStay</div>' +
      '<div class="title">' + headerTitle + '</div>' +
      '<div class="subtitle">' + headerSubtitle + '</div>' +
      (dateRange ? '<div class="date-badge">📅 ' + dateRange + '</div>' : '') +
    '</div>' +
    body +
    '<div class="footer">' +
      '<div class="footer-left">Generated by <span class="footer-brand">ThabStay</span> &bull; ' + dateStr + ' at ' + timeStr + '</div>' +
      '<div class="footer-right">Confidential &bull; Page 1</div>' +
    '</div>' +
  '</body></html>';
};

const buildStatCards = (stats) => {
  let cards = '';
  for (let i = 0; i < stats.length; i++) {
    cards += '<div class="stat-card"><div class="stat-value" style="color:' + stats[i].color + ';">' + stats[i].value + '</div><div class="stat-label">' + stats[i].label + '</div></div>';
  }
  return '<div class="stats-row">' + cards + '</div>';
};

const buildTable = (headers, rows) => {
  let ths = '';
  for (let i = 0; i < headers.length; i++) ths += '<th>' + headers[i] + '</th>';
  let trs = '';
  for (let i = 0; i < rows.length; i++) {
    const isTotal = rows[i]._total;
    let tds = '';
    const cells = rows[i]._total ? rows[i].cells : rows[i];
    for (let j = 0; j < cells.length; j++) tds += '<td>' + cells[j] + '</td>';
    trs += '<tr' + (isTotal ? ' class="total-row"' : '') + '>' + tds + '</tr>';
  }
  if (rows.length === 0) {
    return '<div class="empty-state">No data found for the selected period</div>';
  }
  return '<table><thead><tr>' + ths + '</tr></thead><tbody>' + trs + '</tbody></table>';
};

const statusBadge = (status) => {
  const s = (status || '').toLowerCase();
  const cls = s === 'pending' ? 'badge-pending' : s === 'accepted' ? 'badge-accepted' : s === 'paid' ? 'badge-paid' : s === 'rejected' ? 'badge-rejected' : '';
  return '<span class="badge ' + cls + '">' + (s.charAt(0).toUpperCase() + s.slice(1)) + '</span>';
};

// ============================
// HTML Generators (return HTML for preview)
// ============================

export const buildPropertiesHTML = (listings, dateRange) => {
  const totalSpots = listings.reduce((a, h) => a + (Number(h.availableSpots) || 0), 0);
  const avgPrice = listings.length > 0 ? (listings.reduce((a, h) => a + (Number(h.price) || 0), 0) / listings.length).toFixed(0) : '0';

  const stats = buildStatCards([
    { label: 'Total Properties', value: listings.length, color: '#3182ce' },
    { label: 'Available Spots', value: totalSpots, color: '#38a169' },
    { label: 'Avg Price', value: 'R' + avgPrice, color: '#dd6b20' },
  ]);

  const table = buildTable(
    ['#', 'Property Title', 'Location', 'Price', 'Spots', 'Gender'],
    listings.map((h, i) => [i + 1, h.title || 'N/A', h.location || 'N/A', 'R' + (h.price || 0), h.availableSpots || 0, h.genderPolicy || 'Mixed'])
  );

  return buildHTML('Properties Report', listings.length + ' properties listed', dateRange,
    stats + '<div class="section-title">Property Listings</div>' + table);
};

export const buildBookingsHTML = (bookings, dateRange) => {
  const pending = bookings.filter(b => b.status === 'pending').length;
  const accepted = bookings.filter(b => b.status === 'accepted').length;
  const paid = bookings.filter(b => b.status === 'paid').length;
  const rejected = bookings.filter(b => b.status === 'rejected').length;

  const stats = buildStatCards([
    { label: 'Pending', value: pending, color: '#d69e2e' },
    { label: 'Accepted', value: accepted, color: '#38a169' },
    { label: 'Paid', value: paid, color: '#3182ce' },
    { label: 'Rejected', value: rejected, color: '#e53e3e' },
  ]);

  const table = buildTable(
    ['#', 'Property', 'Student', 'Amount', 'Status', 'Date'],
    bookings.map((b, i) => [
      i + 1, b.houseName || b.houseTitle || 'N/A', b.studentEmail || b.studentName || 'N/A',
      'R' + (b.amount || 0), statusBadge(b.status),
      b.timestamp ? new Date(b.timestamp).toLocaleDateString() : 'N/A'
    ])
  );

  return buildHTML('Booking Summary', bookings.length + ' total bookings', dateRange,
    stats + '<div class="section-title">All Bookings</div>' + table);
};

export const buildRevenueHTML = (bookings, dateRange) => {
  const paidBookings = bookings.filter(b => b.status === 'paid');
  const totalRevenue = paidBookings.reduce((a, b) => a + (Number(b.amount) || 0), 0);
  const avgTx = paidBookings.length > 0 ? (totalRevenue / paidBookings.length).toFixed(0) : '0';

  const stats = buildStatCards([
    { label: 'Total Revenue', value: 'R' + totalRevenue, color: '#38a169' },
    { label: 'Transactions', value: paidBookings.length, color: '#3182ce' },
    { label: 'Average', value: 'R' + avgTx, color: '#dd6b20' },
  ]);

  const rows = paidBookings.map((b, i) => [
    i + 1, b.houseName || b.houseTitle || 'N/A', b.studentEmail || 'N/A',
    'R' + (b.amount || 0), b.transactionId || 'N/A',
    b.paymentDate ? new Date(b.paymentDate).toLocaleDateString() : 'N/A'
  ]);
  rows.push({ _total: true, cells: ['', '', '', '<b>R' + totalRevenue + '</b>', '', '<b>TOTAL</b>'] });

  const table = buildTable(['#', 'Property', 'Student', 'Amount', 'Trans ID', 'Date'], rows);

  return buildHTML('Revenue Report', 'Total Revenue: R' + totalRevenue, dateRange,
    stats + '<div class="section-title">Payment Transactions</div>' + table);
};

export const buildPlatformOverviewHTML = (users, houses, dateRange) => {
  const students = users.filter(u => u.role === 'student').length;
  const landlords = users.filter(u => u.role === 'landlord').length;
  const admins = users.filter(u => u.role === 'admin').length;

  const stats = buildStatCards([
    { label: 'Total Users', value: users.length, color: '#3182ce' },
    { label: 'Students', value: students, color: '#38a169' },
    { label: 'Landlords', value: landlords, color: '#dd6b20' },
    { label: 'Listings', value: houses.length, color: '#805ad5' },
  ]);

  const locationCounts = {};
  houses.forEach(h => { const loc = h.location || 'Unknown'; locationCounts[loc] = (locationCounts[loc] || 0) + 1; });
  const locRows = Object.entries(locationCounts).map(([loc, count]) => [loc, count, ((count / (houses.length || 1)) * 100).toFixed(1) + '%']);
  const locTable = buildTable(['Location', 'Listings', 'Share'], locRows);

  const usersTotal = users.length || 1;
  const roleTable = buildTable(['Role', 'Count', 'Share'], [
    ['Students', students, ((students / usersTotal) * 100).toFixed(1) + '%'],
    ['Landlords', landlords, ((landlords / usersTotal) * 100).toFixed(1) + '%'],
    ['Admins', admins, ((admins / usersTotal) * 100).toFixed(1) + '%'],
  ]);

  return buildHTML('Platform Overview', 'System snapshot', dateRange,
    stats + '<div class="section-title">Listings by Location</div>' + locTable +
    '<div class="section-title">User Distribution</div>' + roleTable);
};

export const buildAllPaymentsHTML = (payments, dateRange) => {
  const totalRevenue = payments.reduce((a, p) => a + (Number(p.amount) || 0), 0);
  const stats = buildStatCards([
    { label: 'Total Revenue', value: 'R' + totalRevenue, color: '#38a169' },
    { label: 'Transactions', value: payments.length, color: '#3182ce' },
  ]);

  const rows = payments.map((p, i) => [
    i + 1, p.houseName || 'N/A', p.studentEmail || 'N/A', 'R' + (p.amount || 0),
    p.transactionId || 'N/A', p.paymentDate ? new Date(p.paymentDate).toLocaleDateString() : 'N/A'
  ]);
  rows.push({ _total: true, cells: ['', '', '<b>TOTAL</b>', '<b>R' + totalRevenue + '</b>', '', ''] });

  const table = buildTable(['#', 'Property', 'Student', 'Amount', 'Trans ID', 'Date'], rows);
  return buildHTML('All Payments Report', payments.length + ' transactions', dateRange,
    stats + '<div class="section-title">Payment Transactions</div>' + table);
};

export const buildUsersHTML = (users, dateRange) => {
  const verified = users.filter(u => u.verificationStatus === 'verified').length;
  const stats = buildStatCards([
    { label: 'Total Users', value: users.length, color: '#3182ce' },
    { label: 'Verified', value: verified, color: '#38a169' },
    { label: 'Unverified', value: users.length - verified, color: '#e53e3e' },
  ]);

  const table = buildTable(['#', 'Name', 'Email', 'Role', 'Status'],
    users.map((u, i) => [
      i + 1, u.username || u.name || 'N/A', u.email || 'N/A',
      (u.role || 'N/A').charAt(0).toUpperCase() + (u.role || '').slice(1),
      u.verificationStatus === 'verified' ? '<span class="badge badge-accepted">Verified</span>' : '<span class="badge badge-rejected">Unverified</span>'
    ])
  );

  return buildHTML('User Management Report', users.length + ' registered users', dateRange,
    stats + '<div class="section-title">All Users</div>' + table);
};

export const buildIssuesHTML = (reports, dateRange) => {
  const table = buildTable(['#', 'Type', 'Reporter', 'Role', 'Description', 'Date'],
    reports.map((r, i) => {
      const desc = r.description || '';
      return [i + 1, r.type || 'Issue', r.reporterEmail || 'N/A', r.reporterRole || 'N/A',
        desc.length > 50 ? desc.substring(0, 50) + '...' : desc,
        r.timestamp ? new Date(r.timestamp).toLocaleDateString() : 'N/A'];
    })
  );

  return buildHTML('Issue Reports', reports.length + ' reports submitted', dateRange,
    '<div class="section-title">All Reported Issues</div>' + table);
};

// ============================
// Legacy PDF export wrappers (still work)
// ============================
export const generatePropertiesPDF = async (listings, dateRange) => { await exportPDF(buildPropertiesHTML(listings, dateRange), 'Properties_Report'); };
export const generateBookingsPDF = async (bookings, dateRange) => { await exportPDF(buildBookingsHTML(bookings, dateRange), 'Booking_Summary'); };
export const generateRevenuePDF = async (bookings, dateRange) => { await exportPDF(buildRevenueHTML(bookings, dateRange), 'Revenue_Report'); };
export const generatePlatformOverviewPDF = async (users, houses, dateRange) => { await exportPDF(buildPlatformOverviewHTML(users, houses, dateRange), 'Platform_Overview'); };
export const generateAllPaymentsPDF = async (payments, dateRange) => { await exportPDF(buildAllPaymentsHTML(payments, dateRange), 'All_Payments'); };
export const generateUsersPDF = async (users, dateRange) => { await exportPDF(buildUsersHTML(users, dateRange), 'User_Report'); };
export const generateIssuesPDF = async (reports, dateRange) => { await exportPDF(buildIssuesHTML(reports, dateRange), 'Issue_Reports'); };

// ============================
// CSV (Excel) Generators
// ============================

const escapeCSV = (val) => {
  const str = String(val != null ? val : '');
  if (str.indexOf(',') >= 0 || str.indexOf('"') >= 0 || str.indexOf('\n') >= 0) {
    return '"' + str.replace(/"/g, '""') + '"';
  }
  return str;
};

export const generateCSV = async (headers, rows, filename) => {
  try {
    const lines = [];
    lines.push(headers.map(escapeCSV).join(','));
    for (let i = 0; i < rows.length; i++) {
      lines.push(rows[i].map(escapeCSV).join(','));
    }
    const csvContent = lines.join('\n');

    if (Platform.OS === 'web') {
      try {
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.setAttribute('href', url);
        link.setAttribute('download', filename + '.csv');
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        setTimeout(function() { URL.revokeObjectURL(url); }, 1000);
      } catch (webErr) {
        console.error('Web CSV Error:', webErr);
      }
    } else {
      const fileUri = FileSystem.documentDirectory + filename + '.csv';
      await FileSystem.writeAsStringAsync(fileUri, csvContent, { encoding: FileSystem.EncodingType.UTF8 });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(fileUri, { mimeType: 'text/csv', dialogTitle: 'Export ' + filename, UTI: 'public.comma-separated-values-text' });
      } else {
        Alert.alert('Success', 'Report saved successfully.');
      }
    }
  } catch (error) {
    console.error('CSV Generation Error:', error);
    if (Platform.OS === 'web') { window.alert('Failed to generate report.'); }
    else { Alert.alert('Error', 'Failed to generate report.'); }
  }
};

export const generatePropertiesCSV = async (listings) => {
  const headers = ['Title', 'Location', 'Price (R)', 'Available Spots', 'Gender Policy', 'Date Listed'];
  const rows = listings.map(h => [h.title || '', h.location || '', h.price || 0, h.availableSpots || 0, h.genderPolicy || 'Mixed', h.createdAt ? new Date(h.createdAt).toLocaleDateString() : 'N/A']);
  await generateCSV(headers, rows, 'Properties_Report');
};

export const generateBookingsCSV = async (bookings) => {
  const headers = ['Property', 'Student', 'Amount (R)', 'Status', 'Transaction ID', 'Date'];
  const rows = bookings.map(b => [b.houseName || b.houseTitle || '', b.studentEmail || b.studentName || '', b.amount || 0, b.status || '', b.transactionId || 'N/A', b.timestamp ? new Date(b.timestamp).toLocaleDateString() : 'N/A']);
  await generateCSV(headers, rows, 'Bookings_Report');
};

export const generatePaymentsCSV = async (payments) => {
  const headers = ['Property', 'Student', 'Amount (R)', 'Transaction ID', 'Payment Date'];
  const rows = payments.map(p => [p.houseName || '', p.studentEmail || '', p.amount || 0, p.transactionId || 'N/A', p.paymentDate ? new Date(p.paymentDate).toLocaleDateString() : 'N/A']);
  await generateCSV(headers, rows, 'Payments_Report');
};

export const generateUsersCSV = async (users) => {
  const headers = ['Name', 'Email', 'Role', 'Verification Status'];
  const rows = users.map(u => [u.username || u.name || 'N/A', u.email || '', u.role || '', u.verificationStatus === 'verified' ? 'Verified' : 'Not Verified']);
  await generateCSV(headers, rows, 'Users_Report');
};

// ============================
// PDF Export with Preview
// ============================

export const exportPDF = async (html, filename) => {
  try {
    if (Platform.OS === 'web') {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(function() { printWindow.print(); }, 500);
      }
    } else {
      // Use printAsync for native preview (shows print dialog with preview)
      await Print.printAsync({ html: html });
    }
  } catch (error) {
    console.error('PDF Error:', error);
    if (Platform.OS === 'web') { window.alert('Failed to generate PDF.'); }
    else { Alert.alert('Error', 'Failed to generate PDF: ' + (error.message || '')); }
  }
};

export const sharePDF = async (html, filename) => {
  try {
    if (Platform.OS === 'web') {
      await exportPDF(html, filename);
      return;
    }
    const result = await Print.printToFileAsync({ html: html, width: 612, height: 792 });
    const newUri = FileSystem.documentDirectory + filename + '_' + Date.now() + '.pdf';
    await FileSystem.moveAsync({ from: result.uri, to: newUri });
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(newUri, { mimeType: 'application/pdf', dialogTitle: 'Share ' + filename, UTI: 'com.adobe.pdf' });
    } else {
      Alert.alert('Success', 'PDF saved successfully.');
    }
  } catch (error) {
    console.error('Share PDF Error:', error);
    Alert.alert('Error', 'Failed to share PDF: ' + (error.message || ''));
  }
};
